name: chess
version: 0.7.0
authors:
  - DongYoon Kang <kdy1@outlook.kr>
  - David Kopec <david@oaksnow.com>
description: A fork of https://github.com/davecom/chess.dart with static typing and json support.
homepage: https://github.com/kdy1/chess.dart
dependencies:
  json_annotation: '^1.0.0'

dev_dependencies:
  test: '^1.3.0'
  benchmark_harness: '>=1.0.0 <1.1.0'
  unittest: '>=0.9.3'
  build_runner: '^0.9.0'
  json_serializable: '^1.0.0'

